### ISSUE TITLE
Form field checkbox style bug

### ISSUE THREAD

**Issue by Zeneo** [nodes-frontend/nodes-ui#13]
There is checkbox in form-group visual vertical align bug when label has margin at top, but not checkbox

**Comment by dennishn** [comment]
I had time to look into this, and it should work. You are probably missing some CSS classes in your markup. Here's an example that works:

```
<div class="form-group">
    <label for="exampleInputSelectB" class="col-sm-2 control-label">Select</label>
    <div class="col-sm-10">
        <select class="form-control" id="exampleInputSelectB" placeholder="Select something">
            <option value="1">Value 1</option>
        </select>
    </div>
</div>
```
- Note that the label is acting as a grid column, and that it has the `control-label` class.
- Note that the select is wrapped in a grid column, and that the select has the `form-control` class.

Let me know if you can't get it to work - closing the issue.
