### ISSUE TITLE
FA-icons on breadcrumbs

### ISSUE THREAD

**Issue by rasmusebbesen** [nodes-frontend/nodes-ui#2]
The "Home"-breadcrumb has a nice house, but when I click deeper into the predefined sub-levels of the backend the breadcrumbs lack font awesome icons
<img width="276" alt="screen shot 2016-02-12 at 14 00 06" src="https://cloud.githubusercontent.com/assets/944158/13007566/881dd486-d191-11e5-8c9e-4cecddafde24.png">

**Comment by dennishn** [comment]
This should be fixed, there should be no icons in breadcrumbs any more. This follows the designs :)
